version: '3'

services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - MONGO_URI=mongodb+srv://admin:voxTaPqIcCC4QvwS@fastapi.3wiu5mv.mongodb.net/?retryWrites=true&w=majority&appName=FastAPI
    depends_on:
      - db
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=voxTaPqIcCC4QvwS
      - MONGO_INITDB_DATABASE=fastapi
